Translated Descriptions (#1)
CheckIO-to-German/Pawn-Brotherhood pull request #3
Opened 2016-10-20 19:50 UTC by DahliaSR

2016-10-21 19:02 UTC, GiForce commented on translations/de/info/task_description.html
> +    Ein Bauer gilt als gedeckt, wenn ein anderer Bauer, der gleichen Farbe, eine gegnerische
> Ein Bauer gilt als gedeckt, wenn ein anderer Bauer, der gleichen Farbe, 

**Ein Bauer gilt als gedeckt, wenn ein anderer Bauer der gleichen Farbe,**

2016-10-21 19:06 UTC, GiForce commented on translations/de/info/task_description.html
> +    Figur auf dessen Feld schlagen kann.<br>
Konjunktiv fände ich angebrachter hier. **...eine gegnerische Figur auf dessen Feld schlagen könnte**

2016-10-21 19:13 UTC, GiForce commented on translations/de/info/task_description.html
> +    <strong>Eingabe: </strong> Die Koordinaten der platzierten weißen Bauern als Set von Strings.
_platzierten_  kann man weglassen, es gibt keine unplatzierten die eine Abgrenzung nötig machten.

2016-10-21 19:15 UTC, GiForce commented on translations/de/info/task_description.html
> +    Spielsituation einschätzen zu können.<br>
>  Eines der wichtigsten Merkmale einer Spiele-KI ist die Fähigkeit **den** aktuelle
> Spielsituation

die aktuelle Spielsituation

2016-10-21 19:21 UTC, GiForce commented on translations/de/info/task_description.html
> +    während die Spalten als Linien bezeichnet und mit den Buchstaben a bis h beschschriftet
**beschschriftet**,
während die Spalten als Linien bezeichnet und mit den Buchstaben a bis h bes**chsch**riftet

2016-10-21 19:23 UTC, GiForce commented on translations/de/info/task_description.html
> +    (z.B.: "a1", "h8", "d6")
Die Klammer in den Satz (hinter das Satzzeichen) nehmen.

2016-10-21 19:29 UTC, GiForce commented on translations/de/info/task_description.html
> +    Diese Aufgabe ist ein sehr simples Beispiel dafür eine solche Fähigkeit zu implementieren.
Dieser Satz ist nicht so schön. Besser: ...ein sehr simples  Beispiel, wie man eine solche Fähigkeit implementieren kann.
oder
..wie wir eine solche Fähigkeit implementieren können.

2016-10-21 19:30 UTC, GiForce requested changes
🎃

2016-10-21 19:38 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    während die Spalten als Linien bezeichnet und mit den Buchstaben a bis h beschschriftet
:white_check_mark:

2016-10-21 19:39 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    (z.B.: "a1", "h8", "d6")
:white_check_mark:

2016-10-21 19:42 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Ein Bauer gilt als gedeckt, wenn ein anderer Bauer, der gleichen Farbe, eine gegnerische
:white_check_mark:

2016-10-21 19:42 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Figur auf dessen Feld schlagen kann.<br>
:white_check_mark:

2016-10-21 19:43 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    <strong>Eingabe: </strong> Die Koordinaten der platzierten weißen Bauern als Set von Strings.
:white_check_mark:

2016-10-21 19:44 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Spielsituation einschätzen zu können.<br>
:white_check_mark:

2016-10-21 19:45 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Diese Aufgabe ist ein sehr simples Beispiel dafür eine solche Fähigkeit zu implementieren.
Stimmt, jetzt wo du es erwähnt hast... :smile: 
:white_check_mark:

2016-10-27 18:40 UTC, GiForce commented on translations/de/info/task_description.html
>  </p>
....eine Zahl (z.B.: "a1", "h8", "d6"). <-- period at the end here, the parantheses.

2016-10-27 18:49 UTC, DahliaSR commented on translations/de/info/task_description.html
>  </p>
:white_check_mark:

2016-10-27 18:49 UTC, GiForce commented on translations/de/info/task_description.html
> +    Diese Aufgabe ist ein sehr simples Beispiel dafür , wie man eine solche Fähigkeit implementieren kann.
...dafür , wie man... -- too much space (b4 the comma)

2016-10-27 19:31 UTC, DahliaSR commented on translations/de/info/task_description.html
> +    Diese Aufgabe ist ein sehr simples Beispiel dafür , wie man eine solche Fähigkeit implementieren kann.
:white_check_mark:

2016-10-27 22:15 UTC, GiForce approved these changes
👍🏻

2016-10-28 17:59 UTC, merged